name: aezip_env
channels:
  - defaults
  - salilab
  - bioconda
  - conda-forge
  - dglteam
dependencies:
  - dgl
  - cudatoolkit
  - python=3.12
  - scikit-learn
  - ipykernel
  - modeller
  - mdtraj
  - biobb_structure_utils
  - biobb_io
  - pip
  - pip:
    - git+https://github.com/bioexcel/biobb_pytorch@dev
