name: aezip_env
channels:
  - defaults
  - salilab
  - bioconda
  - conda-forge
dependencies:
  - dgl
  - cudatoolkit
  - python=3.12
  - scikit-learn==1.7.2
  - ipykernel
  - modeller
  - biobb_structure_utils
  - pip
  - pip:
    - git+https://github.com/bioexcel/biobb_pytorch@dev
