name: aezip_env

channels:
  - dglteam           
  - conda-forge
  - bioconda      
  - defaults

dependencies:
  - python=3.12

  - cudatoolkit
  - dglteam::dgl
  - bioconda::biobb_pytorch
  - conda-forge::scikit-learn

  - pip
  - pip:
      - git+http://github.com/huhlim/cg2all@cuda-12
